name: {{.Project}}
jobs:
  - name: build-{{.PR}}
    noAgent: true
    triggers:
      githubHook: true
    pipeline:
      kind: build
      parameters:
        command: bash scripts/build.sh

  - name: deploy-{{.PR}}
    node: {{ .Project }}-{{.PR}}
    instance:
      arch: arm
      type: t4g.medium
      k8s: true
      health:
        port: 80
        statusCode: 200
        path: /health
    triggers:
      upstream: build-{{.PR}}
    secrets:
      vault:
        envFolder: deployment/k8s/overlays/prenv/env
    commands:
      - TAG=PRE-{{.PR}} deployment/deploy.kargo.sh

  - name: tag-{{.PR}}
    when:
      branch: main
    node: build
    triggers:
      upstream: deploy-{{.PR}}
    pipeline:
      kind: tag
      parameters:
        onlyECR: true
        services:
          - simpler-service3
