apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-gateway.yaml
  - ratelimit-valkey.yaml
  - gateway-routes.yaml
  - gateway-rate-limits.yaml
  - gateway-xff-policy.yaml
